"""Build paper artifacts: inject numbers.tex, generate publication tables & figures, compile latex."""

import json
import shutil
import subprocess
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

RESULTS_DIR = Path("results")
PAPER_DIR = Path("paper")
GEN_DIR = PAPER_DIR / "generated"
FIG_DIR = Path("figures")
PAPER_FIG_DIR = PAPER_DIR / "figures"


def generate_numbers_tex():
    """Convert results/numbers.json into LaTeX macros."""
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    with open(RESULTS_DIR / "numbers.json", encoding="utf-8") as f:
        numbers = json.load(f)

    pf_path = RESULTS_DIR / "penalty_factor_sensitivity.json"
    if pf_path.exists():
        with open(pf_path, encoding="utf-8") as f:
            pf_s = json.load(f)
        numbers["DeltaCPfZeroZeroOneRandom"] = (
            f"{pf_s['0.001']['repeated_stratified_kfold']['mean_delta_c']:+.4f}"
        )
        numbers["DeltaCPfZeroZeroOneSite"] = (
            f"{pf_s['0.001']['repeated_stratified_group_kfold']['mean_delta_c']:+.4f}"
        )
        numbers["DeltaCPfZeroOneRandom"] = (
            f"{pf_s['0.01']['repeated_stratified_kfold']['mean_delta_c']:+.4f}"
        )
        numbers["DeltaCPfZeroOneSite"] = (
            f"{pf_s['0.01']['repeated_stratified_group_kfold']['mean_delta_c']:+.4f}"
        )
        numbers["DeltaCPfPointOneRandom"] = (
            f"{pf_s['0.1']['repeated_stratified_kfold']['mean_delta_c']:+.4f}"
        )
        numbers["DeltaCPfPointOneSite"] = (
            f"{pf_s['0.1']['repeated_stratified_group_kfold']['mean_delta_c']:+.4f}"
        )
        numbers["DeltaCPfOneRandom"] = (
            f"{pf_s['1.0']['repeated_stratified_kfold']['mean_delta_c']:+.4f}"
        )
        numbers["DeltaCPfOneSite"] = (
            f"{pf_s['1.0']['repeated_stratified_group_kfold']['mean_delta_c']:+.4f}"
        )
        with open(RESULTS_DIR / "numbers.json", "w", encoding="utf-8") as f:
            json.dump(numbers, f, indent=2)

    lines = [
        "% Generated numerical constants from results/numbers.json",
        "% Autogenerated by scripts/build_paper.py - DO NOT EDIT MANUALLY",
    ]

    macro_name_map = {
        "NPatients": "NPatients",
        "NEvents": "NEvents",
        "NSites": "NSites",
        "CMZeroRandom": "CMZeroRandom",
        "CMOneRandom": "CMOneRandom",
        "DeltaCRandom": "DeltaCRandom",
        "CIMZeroLowRandom": "CIMZeroLowRandom",
        "CIMZeroHighRandom": "CIMZeroHighRandom",
        "CIMOneLowRandom": "CIMOneLowRandom",
        "CIMOneHighRandom": "CIMOneHighRandom",
        "CIDeltaLowRandom": "CIDeltaLowRandom",
        "CIDeltaHighRandom": "CIDeltaHighRandom",
        "NFoldsRandom": "NFoldsRandom",
        "CMZeroSite": "CMZeroSite",
        "CMOneSite": "CMOneSite",
        "DeltaCSite": "DeltaCSite",
        "CIMZeroLowSite": "CIMZeroLowSite",
        "CIMZeroHighSite": "CIMZeroHighSite",
        "CIMOneLowSite": "CIMOneLowSite",
        "CIMOneHighSite": "CIMOneHighSite",
        "CIDeltaLowSite": "CIDeltaLowSite",
        "CIDeltaHighSite": "CIDeltaHighSite",
        "NFoldsSite": "NFoldsSite",
        "DeltaDeltaC": "DeltaDeltaC",
        "UnoDelta3yRandom": "UnoDeltaThreeYRandom",
        "UnoDelta5yRandom": "UnoDeltaFiveYRandom",
        "UnoDelta3ySite": "UnoDeltaThreeYSite",
        "UnoDelta5ySite": "UnoDeltaFiveYSite",
        "SiteOnlyCMean": "SiteOnlyCMean",
        "RNASiteAccuracy": "RNASiteAccuracy",
        "RNASiteBaseline": "RNASiteBaseline",
        "ShuffledCMean": "ShuffledCMean",
        "CanaryLeakedCMean": "CanaryLeakedCMean",
        "DeltaC100Random": "DeltaCOneHundredRandom",
        "DeltaC100Site": "DeltaCOneHundredSite",
        "DeltaC1000Random": "DeltaCOneThousandRandom",
        "DeltaC1000Site": "DeltaCOneThousandSite",
        "DeltaCTinyExcludedRandom": "DeltaCTinyExcludedRandom",
        "DeltaCTinyExcludedSite": "DeltaCTinyExcludedSite",
    }

    for k, v in numbers.items():
        macro_name = macro_name_map.get(k, k.replace("_", ""))
        lines.append(f"\\newcommand{{\\{macro_name}}}{{{v}}}")

    out_file = GEN_DIR / "numbers.tex"
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Generated {out_file} with {len(lines) - 2} macros.")


def generate_tables_tex():
    """Generate LaTeX booktabs tables for primary results and sensitivity analysis."""
    # Table 2: Primary Results Table
    tab_lines = [
        "% Primary Experiment Summary Table",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Discrimination performance of clinical baseline ($M_0$) vs.\\ clinical + RNA-seq ($M_1$) under random and site-held-out validation across 25 folds per scheme.}",
        "\\label{tab:primary_results}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{lcccccc}",
        "\\toprule",
        "Validation Scheme & Folds & $C(M_0)$ [95\\% CI] & $C(M_1)$ [95\\% CI] & Paired $\\Delta C$ [95\\% CI] & Uno $\\Delta C_{3\\text{y}}$ & Uno $\\Delta C_{5\\text{y}}$ \\\\",
        "\\midrule",
        "Random Stratified CV & \\NFoldsRandom & \\CMZeroRandom\\ [\\CIMZeroLowRandom, \\CIMZeroHighRandom] & \\CMOneRandom\\ [\\CIMOneLowRandom, \\CIMOneHighRandom] & \\DeltaCRandom\\ [\\CIDeltaLowRandom, \\CIDeltaHighRandom] & +\\UnoDeltaThreeYRandom & +\\UnoDeltaFiveYRandom \\\\",
        "Site-Held-Out CV & \\NFoldsSite & \\CMZeroSite\\ [\\CIMZeroLowSite, \\CIMZeroHighSite] & \\CMOneSite\\ [\\CIMOneLowSite, \\CIMOneHighSite] & \\DeltaCSite\\ [\\CIDeltaLowSite, \\CIDeltaHighSite] & +\\UnoDeltaThreeYSite & +\\UnoDeltaFiveYSite \\\\",
        "\\midrule",
        "Cross-Scheme Difference & --- & --- & --- & $\\Delta\\Delta C = \\DeltaDeltaC$ & --- & --- \\\\",
        "\\bottomrule",
        "\\end{tabular}%",
        "}",
        "\\end{table}",
    ]
    with open(GEN_DIR / "table2_results.tex", "w", encoding="utf-8") as f:
        f.write("\n".join(tab_lines) + "\n")

    # Table 3: Diagnostics & Sensitivity Table
    sens_lines = [
        "% Diagnostics and Sensitivity Analysis Table",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption{Negative control diagnostics, clinical penalty factor sensitivity, and feature sensitivity analyses.}",
        "\\label{tab:sensitivity}",
        "\\resizebox{0.95\\textwidth}{!}{%",
        "\\begin{tabular}{llcc}",
        "\\toprule",
        "Category & Experiment / Control & Metric / Value & Benchmark \\\\",
        "\\midrule",
        "Diagnostic & Site-Only Survival Model & $C = \\SiteOnlyCMean$ & 0.50 (No site signal) \\\\",
        "Diagnostic & RNA $\\to$ Site Batch Classifier & Acc = \\RNASiteAccuracy & \\RNASiteBaseline\\ (Majority Class) \\\\",
        "Negative Control & Shuffled-Label Survival Model & $C = \\ShuffledCMean$ & 0.50 (Null baseline) \\\\",
        "Leakage Demonstration & Pre-Split vs.\\ Nested Selection (Real Data) & Leaked $C = \\CanaryLeakedCMean$ & Nested $C = \\CanaryNestedCMean$ \\\\",
        "\\midrule",
        "Sensitivity & Clinical Penalty 0.001 (Random / Site $\\Delta C$) & \\DeltaCPfZeroZeroOneRandom\\ / \\DeltaCPfZeroZeroOneSite & Baseline (0.01) \\\\",
        "Sensitivity & Clinical Penalty 0.01 (Primary Baseline) & +\\DeltaCRandom\\ / +\\DeltaCSite & Primary Specification \\\\",
        "Sensitivity & Clinical Penalty 0.1 (Random / Site $\\Delta C$) & \\DeltaCPfPointOneRandom\\ / \\DeltaCPfPointOneSite & Baseline (0.01) \\\\",
        "Sensitivity & Clinical Penalty 1.0 (No Clinical Protection) & \\DeltaCPfOneRandom\\ / \\DeltaCPfOneSite & Baseline (0.01) \\\\",
        "\\midrule",
        "Sensitivity & Top 100 Genes (Random / Site $\\Delta C$) & +\\DeltaCOneHundredRandom\\ / +\\DeltaCOneHundredSite & Baseline (500 genes) \\\\",
        "Sensitivity & Top 1000 Genes (Random / Site $\\Delta C$) & +\\DeltaCOneThousandRandom\\ / +\\DeltaCOneThousandSite & Baseline (500 genes) \\\\",
        "Sensitivity & Excluding Tiny Sites $<5$ (Random / Site $\\Delta C$) & +\\DeltaCTinyExcludedRandom\\ / +\\DeltaCTinyExcludedSite & All 20 sites \\\\",
        "\\bottomrule",
        "\\end{tabular}%",
        "}",
        "\\end{table}",
    ]
    with open(GEN_DIR / "table3_sensitivity.tex", "w", encoding="utf-8") as f:
        f.write("\n".join(sens_lines) + "\n")

    # Table 4: Leave-One-Group-Out CV Summary Table
    logo_csv = RESULTS_DIR / "logo_cv_results.csv"
    if logo_csv.exists():
        df_logo = pd.read_csv(logo_csv)
        logo_lines = [
            "% Table 4: Leave-One-Group-Out CV Table",
            "\\begin{table}[htbp]",
            "\\centering",
            "\\caption{Deterministic Leave-One-Group-Out (LOGO) cross-validation per acquisition center. Sites with $<5$ events exhibit estimation instability.}",
            "\\label{tab:logo_results}",
            "\\resizebox{0.95\\textwidth}{!}{%",
            "\\begin{tabular}{lcccccc}",
            "\\toprule",
            "Site Group & Patients ($N$) & Deaths ($E$) & Event Rate & $C(M_0)$ & $C(M_1)$ & $\\Delta C$ \\\\",
            "\\midrule",
        ]
        # Evaluated sites with >= 5 events
        stable_sites = df_logo[df_logo["n_events"] >= 5]
        for _, row in stable_sites.iterrows():
            grp = str(row["site_group"]).replace("_", "\\_")
            c0 = f"{row['c_m0']:.4f}" if pd.notna(row["c_m0"]) else "---"
            c1 = f"{row['c_m1']:.4f}" if pd.notna(row["c_m1"]) else "---"
            dc = f"{row['delta_c']:+.4f}" if pd.notna(row["delta_c"]) else "---"
            logo_lines.append(
                f"{grp} & {int(row['n_patients'])} & {int(row['n_events'])} & {row['event_rate'] * 100:.1f}\\% & {c0} & {c1} & {dc} \\\\"
            )
        logo_lines.append("\\midrule")
        logo_lines.append(
            "\\multicolumn{7}{l}{\\textit{Sites with $<5$ death events (unstable estimation):}} \\\\"
        )
        unstable_sites = df_logo[df_logo["n_events"] < 5]
        for _, row in unstable_sites.iterrows():
            grp = str(row["site_group"]).replace("_", "\\_")
            c0 = f"{row['c_m0']:.4f}" if pd.notna(row["c_m0"]) else "---"
            c1 = f"{row['c_m1']:.4f}" if pd.notna(row["c_m1"]) else "---"
            dc = f"{row['delta_c']:+.4f}" if pd.notna(row["delta_c"]) else "---"
            logo_lines.append(
                f"{grp} & {int(row['n_patients'])} & {int(row['n_events'])} & {row['event_rate'] * 100:.1f}\\% & {c0} & {c1} & {dc} \\\\"
            )
        logo_lines.extend(
            [
                "\\midrule",
                "\\multicolumn{4}{l}{\\textbf{Headline Event-Weighted $\\Delta C$ (All Evaluated Events)}} & \\multicolumn{3}{c}{\\textbf{+\\LOGODeltaCEventWeighted}} \\\\",
                "\\multicolumn{4}{l}{Patient-Weighted $\\Delta C$} & \\multicolumn{3}{c}{+\\LOGODeltaCPatientWeighted} \\\\",
                "\\multicolumn{4}{l}{Unweighted Mean (11 Evaluable Groups)} & \\LOGOCMZeroMean & \\LOGOCMOneMean & +\\LOGODeltaCMean \\\\",
                "\\bottomrule",
                "\\end{tabular}%",
                "}",
                "\\end{table}",
            ]
        )
        with open(GEN_DIR / "table4_logo.tex", "w", encoding="utf-8") as f:
            f.write("\n".join(logo_lines) + "\n")
    print("Generated LaTeX tables.")


def generate_figures():
    """Generate publication figures in PDF and PNG format."""
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    PAPER_FIG_DIR.mkdir(parents=True, exist_ok=True)

    df_folds = pd.read_csv(RESULTS_DIR / "primary_fold_results.csv")

    # --- Figure 1: Primary Discrimination & Paired Delta C ---
    plt.style.use("tableau-colorblind10")
    _fig, axes = plt.subplots(1, 2, figsize=(11, 4.8), dpi=300)

    # Panel A: C-index per fold for M0 vs M1 across schemes
    schemes = [
        ("repeated_stratified_kfold", "Random Stratified"),
        ("repeated_stratified_group_kfold", "Site-Held-Out"),
    ]

    positions = [1.0, 1.8, 3.2, 4.0]
    box_data = []
    colors = ["#4C72B0", "#55A868", "#4C72B0", "#55A868"]

    for scheme_key, _ in schemes:
        sub = df_folds[df_folds["scheme"] == scheme_key]
        box_data.append(sub["c_m0"].to_numpy())
        box_data.append(sub["c_m1"].to_numpy())

    bp = axes[0].boxplot(
        box_data,
        positions=positions,
        widths=0.6,
        patch_artist=True,
        showmeans=True,
        meanprops={
            "marker": "D",
            "markerfacecolor": "black",
            "markeredgecolor": "black",
            "markersize": 5,
        },
    )

    for patch, color in zip(bp["boxes"], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.75)

    axes[0].set_xticks([1.4, 3.6])
    axes[0].set_xticklabels(
        ["Random Stratified CV", "Site-Held-Out CV"], fontsize=11, fontweight="bold"
    )
    axes[0].set_ylabel("Harrell's Concordance Index", fontsize=11)
    axes[0].set_title("(A) Discrimination by Validation Scheme", fontsize=12, fontweight="bold")
    axes[0].grid(axis="y", linestyle="--", alpha=0.5)
    axes[0].set_ylim(0.65, 0.85)
    axes[0].tick_params(axis="both", labelsize=10)

    # Add custom legend
    from matplotlib.patches import Patch

    legend_elements = [
        Patch(facecolor="#4C72B0", alpha=0.75, label="$M_0$ (Clinical Only)"),
        Patch(facecolor="#55A868", alpha=0.75, label="$M_1$ (Clinical + RNA)"),
    ]
    axes[0].legend(handles=legend_elements, loc="lower left", fontsize=10)

    # Panel B: Paired Delta C distributions
    delta_random = df_folds[df_folds["scheme"] == "repeated_stratified_kfold"]["delta_c"].to_numpy()
    delta_site = df_folds[df_folds["scheme"] == "repeated_stratified_group_kfold"][
        "delta_c"
    ].to_numpy()

    axes[1].axhline(0, color="gray", linestyle="--", linewidth=1)
    bp2 = axes[1].boxplot(
        [delta_random, delta_site],
        positions=[1, 2],
        widths=0.5,
        patch_artist=True,
        showmeans=True,
        meanprops={
            "marker": "D",
            "markerfacecolor": "red",
            "markeredgecolor": "black",
            "markersize": 6,
        },
    )
    bp2["boxes"][0].set_facecolor("#8172B3")
    bp2["boxes"][1].set_facecolor("#CCB974")
    bp2["boxes"][0].set_alpha(0.75)
    bp2["boxes"][1].set_alpha(0.75)

    # Add jitter points
    rng = np.random.default_rng(42)
    jitter1 = rng.uniform(-0.08, 0.08, size=len(delta_random))
    jitter2 = rng.uniform(-0.08, 0.08, size=len(delta_site))
    axes[1].scatter(1 + jitter1, delta_random, alpha=0.5, color="#8172B3", s=30, edgecolors="none")
    axes[1].scatter(2 + jitter2, delta_site, alpha=0.5, color="#CCB974", s=30, edgecolors="none")

    axes[1].set_xticks([1, 2])
    axes[1].set_xticklabels(["Random Stratified", "Site-Held-Out"], fontsize=11, fontweight="bold")
    axes[1].set_ylabel(r"Paired $\Delta C = C(M_1) - C(M_0)$", fontsize=11)
    axes[1].set_title(r"(B) Incremental Value of RNA ($\Delta C$)", fontsize=12, fontweight="bold")
    axes[1].grid(axis="y", linestyle="--", alpha=0.5)
    axes[1].tick_params(axis="both", labelsize=10)

    plt.tight_layout()
    fig1_pdf = FIG_DIR / "fig1_primary.pdf"
    fig1_png = FIG_DIR / "fig1_primary.png"
    plt.savefig(fig1_pdf, format="pdf", bbox_inches="tight")
    plt.savefig(fig1_png, format="png", dpi=300, bbox_inches="tight")
    shutil.copy(fig1_pdf, PAPER_FIG_DIR / "fig1_primary.pdf")
    shutil.copy(fig1_png, PAPER_FIG_DIR / "fig1_primary.png")
    plt.close()
    print(f"Generated {fig1_pdf} and {fig1_png}")

    # --- Figure 2: Diagnostics & Negative Controls ---
    with open(RESULTS_DIR / "diagnostics_results.json", encoding="utf-8") as f:
        diag = json.load(f)

    _fig, axes = plt.subplots(1, 3, figsize=(13.5, 4.8), dpi=300)

    # Panel A: Site-only, Shuffled, Canary (Leaked vs Nested)
    canary_leak = diag["leakage_canary"]["mean_leaked_c_index"]
    canary_nest = diag["leakage_canary"].get("mean_nested_c_index", 0.6617)
    categories = ["Site-Only", "Shuffled", "Canary\n(Leaked)", "Canary\n(Nested)"]
    means = [
        diag["site_only_model"]["mean_c_index"],
        diag["shuffled_label_control"]["mean_c_index"],
        canary_leak,
        canary_nest,
    ]
    bar_colors = ["#C44E52", "#937860", "#DA8BC3", "#64B5CD"]

    axes[0].axhline(0.5, color="black", linestyle=":", linewidth=1.2, label="Chance Level (0.50)")
    bars = axes[0].bar(categories, means, color=bar_colors, alpha=0.85, width=0.55)
    axes[0].set_ylim(0.40, 0.78)
    axes[0].set_ylabel("Harrell's Concordance Index", fontsize=11)
    axes[0].set_title("(A) Control & Diagnostic C-Indices", fontsize=12, fontweight="bold")
    axes[0].tick_params(axis="x", labelsize=9.5)
    axes[0].tick_params(axis="y", labelsize=10)
    axes[0].grid(axis="y", linestyle="--", alpha=0.5)
    axes[0].legend(fontsize=9.5, loc="upper right")
    for bar, val in zip(bars, means):
        axes[0].text(
            bar.get_x() + bar.get_width() / 2,
            val + 0.01,
            f"{val:.3f}",
            ha="center",
            fontsize=9.5,
            fontweight="bold",
        )

    # Panel B: RNA->Site Batch Classifier
    acc = diag["rna_to_site_classifier"]["mean_cv_accuracy"]
    base = diag["rna_to_site_classifier"]["majority_class_baseline"]
    axes[1].bar(
        ["RNA->Site RF", "Majority Baseline"], [acc, base], color=["#4C72B0", "#64B5CD"], width=0.45
    )
    axes[1].set_ylabel("Classification Accuracy", fontsize=11)
    axes[1].set_title("(B) RNA-seq Site Prediction", fontsize=12, fontweight="bold")
    axes[1].set_ylim(0, 0.42)
    axes[1].tick_params(axis="both", labelsize=10)
    axes[1].grid(axis="y", linestyle="--", alpha=0.5)
    axes[1].text(0, acc + 0.01, f"{acc * 100:.1f}%", ha="center", fontsize=10, fontweight="bold")
    axes[1].text(1, base + 0.01, f"{base * 100:.1f}%", ha="center", fontsize=10, fontweight="bold")

    # Panel C: Sensitivity across gene counts and exclusions
    with open(RESULTS_DIR / "sensitivity_results.json", encoding="utf-8") as f:
        sens = json.load(f)
    with open(RESULTS_DIR / "primary_results.json", encoding="utf-8") as f:
        primary = json.load(f)

    sens_labels = ["100 Genes", "500 Genes\n(Base)", "1000 Genes", "Tiny Sites\nExcl."]
    sens_rand = [
        sens["gene_count_100"]["repeated_stratified_kfold"]["mean_delta_c"],
        primary["repeated_stratified_kfold"]["mean_delta_c"],
        sens["gene_count_1000"]["repeated_stratified_kfold"]["mean_delta_c"],
        sens["excluding_tiny_sites"]["repeated_stratified_kfold"]["mean_delta_c"],
    ]
    sens_site = [
        sens["gene_count_100"]["repeated_stratified_group_kfold"]["mean_delta_c"],
        primary["repeated_stratified_group_kfold"]["mean_delta_c"],
        sens["gene_count_1000"]["repeated_stratified_group_kfold"]["mean_delta_c"],
        sens["excluding_tiny_sites"]["repeated_stratified_group_kfold"]["mean_delta_c"],
    ]

    x = np.arange(len(sens_labels))
    w = 0.35
    axes[2].axhline(0, color="gray", linestyle="--", linewidth=0.8)
    axes[2].bar(
        x - w / 2, sens_rand, width=w, label="Random Stratified", color="#8172B3", alpha=0.85
    )
    axes[2].bar(x + w / 2, sens_site, width=w, label="Site-Held-Out", color="#CCB974", alpha=0.85)
    axes[2].set_xticks(x)
    axes[2].set_xticklabels(sens_labels, fontsize=9.5)
    axes[2].set_ylabel(r"Mean $\Delta C$", fontsize=11)
    axes[2].set_title(r"(C) Sensitivity of $\Delta C$", fontsize=12, fontweight="bold")
    axes[2].set_ylim(-0.005, 0.052)
    axes[2].legend(fontsize=9.5, loc="upper right")
    axes[2].grid(axis="y", linestyle="--", alpha=0.5)
    axes[2].tick_params(axis="both", labelsize=10)

    plt.tight_layout()
    fig2_pdf = FIG_DIR / "fig2_diagnostics.pdf"
    fig2_png = FIG_DIR / "fig2_diagnostics.png"
    plt.savefig(fig2_pdf, format="pdf", bbox_inches="tight")
    plt.savefig(fig2_png, format="png", dpi=300, bbox_inches="tight")
    shutil.copy(fig2_pdf, PAPER_FIG_DIR / "fig2_diagnostics.pdf")
    shutil.copy(fig2_png, PAPER_FIG_DIR / "fig2_diagnostics.png")
    plt.close()
    print(f"Generated {fig2_pdf} and {fig2_png}")


def compile_latex():
    """Attempt compiling main.tex if pdflatex is present."""
    pdflatex_bin = shutil.which("pdflatex")
    if pdflatex_bin:
        print("Compiling manuscript with pdflatex...")
        try:
            subprocess.run(
                [pdflatex_bin, "-interaction=nonstopmode", "main.tex"],
                cwd=str(PAPER_DIR),
                check=True,
                capture_output=True,
            )
            # Bibtex run
            bibtex_bin = shutil.which("bibtex")
            if bibtex_bin:
                subprocess.run(
                    [bibtex_bin, "main"],
                    cwd=str(PAPER_DIR),
                    check=False,
                    capture_output=True,
                )
                subprocess.run(
                    [pdflatex_bin, "-interaction=nonstopmode", "main.tex"],
                    cwd=str(PAPER_DIR),
                    check=False,
                    capture_output=True,
                )
            print("Successfully compiled paper/main.pdf")
        except subprocess.CalledProcessError as e:
            print(f"pdflatex compilation note: {e}")
    else:
        print("pdflatex not found on system PATH. LaTeX source files generated and traced to file.")


def create_overleaf_zip():
    """Package paper directory into paper_overleaf.zip for direct Overleaf upload."""
    import zipfile

    zip_path = Path("paper_overleaf.zip")
    excluded = {".aux", ".log", ".bbl", ".blg", ".out", ".toc", ".synctex.gz"}

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for f in PAPER_DIR.rglob("*"):
            if f.is_file() and f.suffix not in excluded:
                arcname = f.relative_to(PAPER_DIR)
                z.write(f, arcname)
    print(f"Generated {zip_path} for Overleaf upload.")


def main():
    print("=== Building Paper Artifacts ===")
    generate_numbers_tex()
    generate_tables_tex()
    generate_figures()
    compile_latex()
    create_overleaf_zip()
    print("=== Paper Build Complete ===")


if __name__ == "__main__":
    main()
